#!/usr/bin/fish

./XX-mcmc-tuning.R fish | source

# set N_ITERATIONS 550
# set BURNIN 50
# set THIN 1

for DISCARD_PROPORTION in 0.0000 0.1000 0.2000 0.3000 0.4000 0.5000
    for RUN in (seq 10)
        if test $DISCARD_PROPORTION -eq 0.0000
            set DROP_SEQ none married race
        else
            set DROP_SEQ none
        end
        for DROP in $DROP_SEQ
            for i in (seq 1 $n_replicates)
                echo RAYON_NUM_THREADS=1 ./XX-mcmc-dependent.R temporal 1994-2020 $DISCARD_PROPORTION 5 1 TRUE 1 1 TRUE TRUE $DROP $N_ITERATIONS $BURNIN $THIN "$i"_"$n_replicates" $RUN
            end
        end
    end
end
